version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: wastrachan/tftpd
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - deploy:
          name: Publish image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push $IMAGE_NAME:latest
            fi
      - run:
          name: Update MicroBadger
          command: |
            curl -X POST 'https://hooks.microbadger.com/images/wastrachan/tftpd/AiyPLeYRd66JjWE419gCo2Jnmuk='

workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
